#!/bin/zsh

# ------PATH------
export PATH=$PATH:/usr/sbin:/usr/local/sbin:$HOME/.local/bin:

# ------Asliases------
source $HOME/.config/shell/aliasrc

# ------Zsh dotfiles------
export ZDOTDIR=$HOME/.config/zsh

# ------Defaults------
export WM="dwm"
export TERMINAL="alacritty"
export EDITOR="nvim"
export BROWSER="librewolf"
#type brave-browser >/dev/null 2>&1 && export PBROWSER="brave-browser"
#type brave >/dev/null 2>&1 && export PBROWSER="brave"
export PBROWSER="ferdi"
export WBROWSER="chromium"
export FM="lf"
export VIEWER="zathura"
export RSSREADER="newsboat"
export PLAYER="ncmpcpp"
export MAIL="neomutt"
#[ $(hostname) = 'Curiosity' ] && export MAIL="neomutt"
#[ $(hostname) = 'Voyager' ] && export MAIL="thunderbird"
export MAIL="thunderbird"
export QT_QPA_PLATFORMTHEME="qt5ct"

# ------Other------
# Fix misbehaving Java applications
export _JAVA_AWT_WM_NONREPARENTING=1

# Disable Recipe Proxying in Franz/Ferdi
alias ferdi='export CONNECT_WITH_FRANZ=false ; ferdi'
