#!/bin/sh

# Verbosity & Confirm before overwritting files
alias rm='rm -vi'
alias mv='mv -vi'
alias cp='cp -vi'

# Verbosity & Create parent directories
alias mkdir='mkdir -vp'

# ls
alias ls='ls --human-readable --literal --color=auto --group-directories-first'
alias ll='ls -l'
alias la='ls -la'
alias l.='ls -a | grep "^\."'
alias ll.='ls -la | grep "^\."'

# grep color
alias grep='grep --color=auto'

# diff
#alias diff='diff --context=3 --ignore-all-space --color=auto' #Context
alias diff='diff --unified=3 --ignore-all-space --color=auto' #Unified

# vim
alias vi='nvim'
alias vim='nvim'
alias neovim='nvim'
alias vimwiki='nvim $HOME/Documents/VimWiki/index.wiki'
alias vimw='nvim $HOME/Documents/VimWiki/index.wiki'

# git
alias init='git init'
alias st='git status'
alias gdiff='git diff'
alias a='git add && git status'
alias aa='git add --all && git status'
alias au='git add --update && git status'
alias ci='git commit -m'
alias pull='git pull'
alias push='git push'

# dotfiles
alias config='git --git-dir=$HOME/Documents/dotfiles/ --work-tree=$HOME'

# youtube-dl
alias music-dl='youtube-dl -x --audio-format mp3'

# apt
alias aptup='sudo apt update && sudo apt upgrade'

# sudo
#alias sudo='sudo EDITOR=nvim ' # zsh completion doesn't work properly
alias sudo='sudo '

# mbsync
alias mbsync='mbsync -a -c $XDG_CONFIG_HOME/mbsync/mbsyncrc'

# mbsync
alias mutt='neomutt'

# UGTABLET
alias settablet='xsetwacom set "UGTABLET 11.6 inch PenDisplay stylus" MapToOutput HEAD-1 ;\
        xsetwacom set "UGTABLET 11.6 inch PenDisplay eraser" MapToOutput HEAD-1 ;\
        xsetwacom set "UGTABLET 11.6 inch PenDisplay stylus" Button 2 3'

# make
alias makebear='make clean; bear -- make'

# fzf
alias open='xdg-open'

alias fcd='cd "$(find -type d | fzf -i)"'
alias fopen='xdg-open "$(find -type f | fzf -i)"'
alias fpath='find -type f | fzf -i | sed "s/^..//" | tr -d "\n" | xclip -selection c'
