#!/bin/sh

# PATH
export PATH=$PATH:/usr/sbin:/usr/local/sbin:$HOME/.local/bin:

# Asliases
source $HOME/.config/shell/aliasrc

# Default Programs
export TERMINAL="terminator"
export EDITOR="nvim"
export BROWSER="firefox"

# Root if I ever bother to fix it
#~/.Root/root/bin/thisroot.sh

# XDG Base Directory
export XDG_CONFIG_HOME="$HOME"/.config
export XDG_CACHE_HOME="$HOME"/.cache
export XDG_DATA_HOME="$HOME"/.local/share

export ANDROID_PREFS_ROOT="$XDG_CONFIG_HOME"/android
export ANDROID_EMULATOR_HOME="$XDG_DATA_HOME"/android/emulator

export CUDA_CACHE_PATH="$XDG_CACHE_HOME"/nv

mkdir -p "$XDG_DATA_HOME"/bash
export HISTFILE="$XDG_DATA_HOME"/bash/history

mkdir $XDG_CONFIG_HOME/git
touch $XDG_CONFIG_HOME/git/config

export GNUPGHOME="$XDG_DATA_HOME"/gnupg

export GTK_RC_FILES="$XDG_CONFIG_HOME"/gtk-1.0/gtkrc
export GTK2_RC_FILES="$XDG_CONFIG_HOME"/gtk-2.0/gtkrc

export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="$XDG_CONFIG_HOME"/java

mkdir -p "$XDG_CACHE_HOME"/less
export LESSKEY="$XDG_CONFIG_HOME"/less/lesskey
export LESSHISTFILE="$XDG_CACHE_HOME"/less/history
export LESSHISTFILE=- #can be used to disable this feature

export MATHEMATICA_USERBASE="$XDG_CONFIG_HOME"/mathematica

mkdir $XDG_CONFIG_HOME/newsboat
mkdir $XDG_DATA_HOME/newsboat

export KODI_DATA="$XDG_DATA_HOME"/kodi

export VIMINIT='source "$XDG_CONFIG_HOME/vim/vimrc"'

mkdir $XDG_CONFIG_HOME/wget 
touch $XDG_CONFIG_HOME/wget/wgetrc
export WGETRC="$XDG_CONFIG_HOME/wget/wgetrc"
alias weget='wget --hsts-file="$XDG_CACHE_HOME/wget-hsts"'

mkdir -p "$XDG_DATA_HOME"/wineprefixes
export WINEPREFIX="$XDG_DATA_HOME"/wineprefixes/default

export XAUTHORITY="$XDG_RUNTIME_DIR"/Xauthority

export HISTFILE="$XDG_DATA_HOME"/zsh/history
mkdir $XDG_CACHE_HOME/zsh/zcompdump-$ZSH_VERSION
compinit -d $XDG_CACHE_HOME/zsh/zcompdump-$ZSH_VERSION
source "$HOME/.cargo/env"
