#!/bin/sh

# PATH
export PATH=$PATH:/usr/sbin:/usr/local/sbin:$HOME/.local/bin:

# Default Programs
export TERMINAL="gnome-terminal"
export EDITOR="nvim"
export BROWSER="firefox"

# Root if I ever bother to fix it
#~/.Root/root/bin/thisroot.sh

# XDG Base Directory
export XDG_CONFIG_HOME="$HOME"/.config
export XDG_CACHE_HOME="$HOME"/.cache
export XDG_DATA_HOME="$HOME"/.local/share

export ANDROID_PREFS_ROOT="$XDG_CONFIG_HOME"/android
export ANDROID_EMULATOR_HOME="$XDG_DATA_HOME"/android/emulator

export CUDA_CACHE_PATH="$XDG_CACHE_HOME"/nv

export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="$XDG_CONFIG_HOME"/java

export MATHEMATICA_USERBASE="$XDG_CONFIG_HOME"/mathematica

export KODI_DATA="$XDG_DATA_HOME"/kodi
